### ISSUE TITLE
TODO - Bugs Fix

### ISSUE THREAD

**Issue by WDever** [WDever/hanlight-frontend-web#10]
Fix Some bugs
- [x] Board Role Panel didn’t follow scroll bug
- [x] Main page lunch timer text position bug
- [x] Detail Calendar Page grid margin and sort

- [x] Merge to develop
- [x] Merge to master
