### ISSUE TITLE
TODO - New Hanlight Music

### ISSUE THREAD

**Issue by WDever** [WDever/hanlight-frontend-web#11]
- [x] rewrite all component
    - [x] main
    - [x] search

- [ ] Desktop UI
- [x] Mobile UI

- [ ] add new components
    - [x] search bar
        - [x] separate category as url
        - [x] floating like header
    - [x] artist
        - [x] separate category as url
    - [x] artist's album
  - [ ] submit button
    - [ ] select logic with redux
 
- [ ] highlight same string in search
- [ ] highlight title song in album

- [ ] connect to artist/album page

- [ ] merge to develop
- [ ] merge to master
- [ ] check production
