### ISSUE TITLE
TODO - IE Block Page

### ISSUE THREAD

**Issue by WDever** [WDever/hanlight-frontend-web#9]
- [x] Add Information page for IE users
- [x] Merge to develop
- [x] Merge to master
- [x] Check Production
